apiVersion: v1
kind: Service
metadata:
  name: {{ include "aegivis.fullname" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aegivis.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    - port: {{ .Values.proxy.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "aegivis.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
