"""Generate Kubernetes NetworkPolicy objects from an AgentSecurityPolicy spec.

Design:
  The proxy sidecar handles hostname-level egress enforcement (already in V1).
  The NetworkPolicy's job is to provide defence-in-depth at the CNI layer:
    - Allow DNS (port 53 UDP/TCP) → kube-dns
    - Allow traffic to the Aegivis backend service
    - Allow all egress from pods in AUDIT mode (records but doesn't block)
    - In ALLOWLIST mode: restrict to DNS + HTTPS only (proxy enforces destinations)

Note: K8s NetworkPolicy cannot filter by hostname, only IP/CIDR.
      The proxy sidecar does the fine-grained hostname allowlist.
      NetworkPolicy provides the coarse-grained "only HTTPS + DNS" layer.
"""
from __future__ import annotations

from typing import Any


def build_network_policy(
    policy_name: str,
    namespace: str,
    spec: dict[str, Any],
) -> dict[str, Any]:
    """Return a NetworkPolicy manifest dict for the given AgentSecurityPolicy spec."""
    selector      = spec.get("selector", {})
    match_labels  = selector.get("matchLabels", {})
    egress_spec   = spec.get("egress", {})
    egress_mode   = egress_spec.get("mode", "audit").lower()

    # Always allow DNS
    dns_rule = {
        "ports": [
            {"port": 53, "protocol": "UDP"},
            {"port": 53, "protocol": "TCP"},
        ],
    }

    # Always allow HTTPS outbound (proxy enforces destinations at Layer 7)
    https_rule = {
        "ports": [{"port": 443, "protocol": "TCP"}],
    }

    # Allow plain HTTP for internal tool endpoints
    http_rule = {
        "ports": [{"port": 80, "protocol": "TCP"}],
    }

    # Allow Aegivis backend (intra-cluster)
    backend_rule = {
        "ports": [{"port": 8000, "protocol": "TCP"}],
    }

    if egress_mode == "off":
        # No NetworkPolicy — don't restrict at all
        return {}

    if egress_mode == "allowlist":
        # Restrict: only DNS + HTTPS + backend, nothing else
        egress_rules = [dns_rule, https_rule, backend_rule]
    else:
        # audit mode: allow all egress (just record via proxy)
        egress_rules = [dns_rule, https_rule, http_rule, backend_rule, {}]
        # {} = wildcard rule (allow all)

    name = f"aegivis-{policy_name}"

    return {
        "apiVersion": "networking.k8s.io/v1",
        "kind": "NetworkPolicy",
        "metadata": {
            "name": name,
            "namespace": namespace,
            "labels": {
                "app.kubernetes.io/managed-by": "aegivis-controller",
                "aegivis.io/policy": policy_name,
            },
            "annotations": {
                "aegivis.io/egress-mode": egress_mode,
                "aegivis.io/note": (
                    "NetworkPolicy generated by Aegivis controller. "
                    "Proxy sidecar enforces hostname-level egress. "
                    "This policy provides IP-level defence-in-depth."
                ),
            },
        },
        "spec": {
            "podSelector": {"matchLabels": match_labels},
            "policyTypes": ["Egress"],
            "egress": egress_rules,
        },
    }


def network_policy_name(policy_name: str) -> str:
    return f"aegivis-{policy_name}"
